[1.34] Fix the CI image tag and SHA
The new image (based on upstream 1.34) is pushed to quay under the same
tag (`cb86d91cf406995012e330ab58830e6ee10240cb`), but because it is now
properly based on the 1.34 upstream image, the content changed,
therefore the SHA changed as well.

The 1.34 image is based on clang 18, hence we needed a couple of fixed
to make prefixer work with it:

- Adjust the include path: In clang 14 the include path is
  `.../clang/14.0.1/include` whereas in clang 18 it is
`.../clang/18/include`.
- Remove a `no_return` clause that was causing the following compile
  error:
```
error: type name does not allow function specifier to be specified
 6167 |   ossl_ossl_noreturn ossl_OPENSSL_die_t ossl_OPENSSL_die;
      |   ^
```

Signed-off-by: Jonh Wendell <jwendell@redhat.com>